### ISSUE TITLE
malloc error

### ISSUE THREAD

**Issue by eddiemoore** [apiaryio/protagonist#60] opened 2015-04-24 03:31 UTC
Running into a malloc error when run from grunt. Doesn't happen all the time, however it doesn't parse the api file at all
https://github.com/eddiemoore/grunt-protagonist/issues/1
```
malloc: *** error for object 0x10140a3b0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Running:**
node v0.12.2
grunt: v0.4.5

**To reproduce:**
```shell
npm install --save-dev grunt-protagonist
```
**example.apib**
```markdown
# Group Users

## Users [/users]
### Create a new user [POST]

+ Attributes

    + email (string, required) - User's email address
    + username (string, required) - Username for user
    + password (string, required) - Password for user

+ Request (application/json)
    + Headers

            Authorization: Bearer ACCESS_TOKEN

    + Body

            {
              "email": "example@example.com",
              "username": "foobar",
              "password": "2xPaisdn",
            }
```

**Gruntfile.js**
```javascript
'use strict'

module.exports = function (grunt) {

  grunt.initConfig({
    protagonist: {
      src: 'example.apib'
    }
  });

  grunt.loadNpmTasks('grunt-protagonist');

  grunt.registerTask('default', ['protagonist']);
}
```

**Run:**
```shell
grunt
```

This should display an error. However it just passes the test and occasionally runs into errors when running the protagonist module

**Comment by pksunkara** [comment] 2015-04-24 04:51
Similar to #59, this blueprint is working for me correctly in drafter.

**Comment by eddiemoore** [comment] 2015-04-24 05:30
Did you try running my example setup?

**Comment by eddiemoore** [comment] 2015-04-24 12:47
@pksunkara What's the difference between protagonist and drafter?

**Comment by pksunkara** [comment] 2015-04-24 12:48
Drafter is the C++ parser which actually parses the API Blueprint. Protagonist is the node.js C++ module which wraps the result from drafter into node.js JSON.

**Comment by eddiemoore** [comment] 2015-04-24 12:51
and https://github.com/apiaryio/drafter.js ?

**Comment by pksunkara** [comment] 2015-04-24 12:52
It is an extra node.js module which expands the API Blueprint AST given by protagonist and used by Apiary. In the future, it's functionality will be moved to drafter.

**Comment by eddiemoore** [comment] 2015-04-24 13:03
So should I be using drafter.js instead

**Comment by pksunkara** [comment] 2015-04-24 14:58
No, you should use protagonist only. Drafter.js is being used inside Apiary for some other reasons.

**Comment by eddiemoore** [comment] 2015-04-24 15:01
Ok then please try my example stated above and you will see the problem.

**Comment by kylef** [comment] 2016-07-21 23:14
At lot has changed in Protagonist since this issue was created. I'm unable to reproduce this problem with the latest versions of Drafter/Protagonist.

@eddiemoore Could you please verify if you are still having this problem with Protagonist 1.4.1.

**Comment by w-vi** [comment] 2016-08-23 13:36
Closing as solved, feel free to reopen if the issue is not fixed or occurs again.

**Closed by w-vi** 2016-08-23 13:36 UTC
Labels: s4: awaiting validation
