### ISSUE TITLE
Support nodejs 3.0 and 4.0

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/protagonist#81] opened 2015-08-12 09:46 UTC
I'm seeing build failures on CI hosts using the recently released iojs 3.0.0:

https://travis-ci.org/danielgtaylor/aglio/jobs/75231420

The issue seems to be related to nan. This other project is moving to nan 2.x to fix a similar issue:

https://github.com/Automattic/node-canvas/issues/606

**Comment by Freundschaft** [comment] 2015-09-09 12:30
yes also it doesnt work right now with nodejs 4.0 as far as i can see

**Comment by pksunkara** [comment] 2015-09-09 14:53
Ah, we need to fix this using nan.

**Comment by splodingsocks** [comment] 2015-09-09 16:23
What's the preferred way for you to know when issues are important to other people? I don't want to spam with +1 here, but I'm interested in throwing in my vote for attention to this issue. I'd love to move to Node 4.0 when possible. Thanks so much for all your work!

**Comment by pksunkara** [comment] 2015-09-09 16:30
@splodingsocks Using +1 is perfectly okay with us. :smile: 

We are working on an important release first and would prefer to not do this until that. Any contributions are welcome though. We have to update the `nan` package version and fix any issues (most probably none) that rise up.

**Comment by splodingsocks** [comment] 2015-09-09 16:34
Okay, great! I wish I were able to dive in right now and figure out how to do this, never having compiled native extensions before. If I'm able to, I'll post back here. If not, I'll just be patient :)

Thanks again!

**Comment by xiphiaz** [comment] 2015-09-10 06:34
+1 This is causing issues with travis ci failing to compile (tried base travis confi, 0.12 & 4.0.0)

**Comment by ChALkeR** [comment] 2015-09-12 17:07
Adding to the list: https://github.com/nodejs/node/issues/2798.
You have to update `nan` to v2.

**Comment by tobiashm** [comment] 2015-09-21 10:08
I've made a PR #90 with an upgrade to Nan 2.0
This was done mostly using a script. It seems to be working fine on my machine with Node 4.0 and 4.1, but it currently fails on the CI builds, so I'm a bit lost on what's wrong.
If anyone has more knowledge about the code could take a look, that would be great, because I actually don't know what I'm doing here :-) I'm not a C/C++ developer.

**Comment by ChALkeR** [comment] 2015-09-21 10:34
@tobiashm Travis builds are failing because they use gcc 4.6, while the minimum supported gcc version is 4.8. Travis config has to be changed.

**Comment by zdne** [comment] 2015-09-21 10:51
> Travis builds are failing because they use gcc 4.6, while the minimum supported gcc version is 4.8. Travis config has to be changed.

So upgrading to support Node.js 3+ implies we discontinue supporting systems with GCC 4.6? /cc @klokane

**Comment by trodrigues** [comment] 2015-09-24 10:14
Not a big deal but also ran into this using https://www.npmjs.com/package/aglio

**Comment by ChALkeR** [comment] 2015-09-24 10:38
@So upgrading to support Node.js 3+ implies we discontinue supporting systems with GCC 4.6? /cc @klokane

No, it doesn't. Afaik, your package will work with old gcc and old node, with new gcc and old node, with new gcc and new node, _but not with old gcc and new node_. Without this patch, your package doesn't work with new node at all.

**Comment by klokane** [comment] 2015-09-24 10:51
I'm going to decide about supported versions of compilers in next week, make some testing and we will see

**Comment by ChALkeR** [comment] 2015-09-24 11:05
Not quite sure what are you going to decide on. Node.js 4.0 won't compile with GCC 4.6.
In order to compile with Node.js 4.0, one should use a more recent gcc version.

**Comment by klokane** [comment] 2015-09-24 11:19
Thanks for link. 

We are thinking about drop support of older version compilers and allow some subset of C++ 11 features in drafter/snowcrash codebase.

**Comment by igrayson** [comment] 2015-09-24 20:46
Looking forward to using 4.0, so +1

**Comment by zanuka** [comment] 2015-09-25 23:07
:+1:

**Comment by fesor** [comment] 2015-09-25 23:11
:+1:

**Comment by dkcwd** [comment] 2015-09-28 11:04
:+1:

**Comment by RapsIn4** [comment] 2015-09-28 17:14
:+1:

**Comment by tbostelmann** [comment] 2015-09-29 15:23
:+1:

**Comment by tobiashm** [comment] 2015-09-29 20:49
There's a lot of support for this issue. If anyone could take a look at #90 and help sorting out the last issues, we might be able to close it :smile_cat:

**Comment by artlogic** [comment] 2015-10-01 05:12
:+1:

**Comment by kalugen** [comment] 2015-10-01 10:03
:+1:

**Comment by zachgersh** [comment] 2015-10-02 21:48
:+1: 
Just hit this today with v4.1.1.

**Comment by natdm** [comment] 2015-10-04 15:38
Hitting it with rpi-gpio. 4.1.1.

**Comment by tobiashm** [comment] 2015-10-07 18:41
Since #90 has been merged, this issue could now be closed.
So now we are just awaiting a new release version ;-)

**Comment by pksunkara** [comment] 2015-10-08 02:33
The master branch now supports nodejs 3.0 and 4.0. We still need to fix a few bugs in apiaryio/drafter and release protagonist.

**Comment by rvlander** [comment] 2015-10-15 15:11
Any idea of when it will be released?

**Comment by pksunkara** [comment] 2015-10-15 15:16
@rvlander We are working on this. There are a few changes which need to be made to Drafter before this can be done.

**Comment by kadishmal** [comment] 2015-10-22 07:10
:+1: Can't upgrade `aglio` due to this issue.

**Comment by ye** [comment] 2015-10-22 15:21
:+1:  I guess this issue is the root cause of this one https://github.com/danielgtaylor/aglio/issues/183

**Comment by kylef** [comment] 2015-10-23 16:59
Thanks for your patience everyone. Protagonist 1.1.0 now supports Node 3 and Node 4.

**NOTE**: Any tooling such as Aglio will need to be moved to use Protagonist 1.1.0.

**Closed by kylef** 2015-10-23 16:59 UTC
Labels: s2: confirmed, t4: feature

**Comment by zanuka** [comment] 2015-10-25 19:49
:+1:

**Comment by ScotterC** [comment] 2015-11-03 16:48
@ChALkeR thanks for this comment https://github.com/apiaryio/protagonist/issues/81#issuecomment-142887797. I had GCC 4.6 and Node 4 and it wasn't working. Downgrading to Node 0.12 fixes the protagonist compilation if you can't upgrade GCC

**Comment by ChALkeR** [comment] 2015-11-03 23:08
@ScotterC I don't recommend downgrading to 0.12.
