### ISSUE TITLE
Error parsing some files.

### ISSUE THREAD

**Issue by apimatic** [apiaryio/protagonist#75] opened 2015-07-04 02:05 UTC
Hi.

We are using protagonist 0.19.3 on NodeJS 0.10.2 on Windows 32bit machine. Every now and then we get a file that refuses to parse properly, but the same file parses correctly on the parser hosted on apiblueprint.org. For example the following:
http://docs.wink.apiary.io/
http://docs.ulozenkav3.apiary.io/

Could it be a configuration issue on our server? Can you tell what version is being used in https://api.apiblueprint.org/parser

Thanks.

**Comment by zdne** [comment] 2015-07-21 12:02
Hey @apimatic the API parsing service is using protagonist v0.20.1 at the moment. You can see its sources [here](https://github.com/apiaryio/apiblueprintorg/blob/master/). 

In the past there were some reports of errors on Windows however we weren't able to reproduce them. Any help to get this squashed would be highly appreciated!

**Comment by kylef** [comment] 2015-09-22 18:49
@apimatic Did you manage to solve this problem?

**Comment by apimatic** [comment] 2015-09-22 23:11
Unfortunately no.

**Comment by kylef** [comment] 2016-07-21 23:19
I'ms still unable to reproduce problems parsing these blueprints with the latest versions of Protagonist (1.4.1) and Drafter.

The API Blueprint does produce a lot of warnings, but it does parse the blueprint.

Can you please elaborate on what the problem is, are there any specific errors? Perhaps this error has been fixed, please test against Protagonist 1.4.1, a lot has changed since Protagonist 0.19.3.

Thanks

**Comment by w-vi** [comment] 2016-08-23 13:37
Closing as it seems out of date, feel free to reopen though.

**Closed by w-vi** 2016-08-23 13:37 UTC
Labels: s4: awaiting validation, t2: bug
