### ISSUE TITLE
Node 0.12 on Mac Support

### ISSUE THREAD

**Issue by mikevalstar** [apiaryio/protagonist#48] opened 2015-03-04 15:49 UTC
When attempting to build protagonist on Mac with node v0.12.0 and xcode 6.1.1 I get the following error:

    > protagonist@0.17.2 install /Users/kg-bohrium/projects/ucp-main/node_modules/gulp-aglio/node_modules/aglio/node_modules/protagonist
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprintSourcemap.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Section.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Signature.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
      CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
      LIBTOOL-STATIC Release/snowcrash.a
      CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/ByteBuffer.o
      CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownNode.o
      CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownParser.o
      LIBTOOL-STATIC Release/markdownparser.a
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
      CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
      LIBTOOL-STATIC Release/sundown.a
      CXX(target) Release/obj.target/protagonist/src/annotation.o
    In file included from ../src/annotation.cc:1:
    ../src/protagonist.h:13:36: error: expected class name
        class Blueprint : public node::ObjectWrap {
                                       ^
    ../src/protagonist.h:28:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
            static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
    /Users/kg-bohrium/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
          ^
    In file included from ../src/annotation.cc:1:
    ../src/protagonist.h:35:36: error: expected class name
        class Sourcemap : public node::ObjectWrap {
                                       ^
    ../src/protagonist.h:50:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
            static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
    /Users/kg-bohrium/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
          ^
    In file included from ../src/annotation.cc:1:
    ../src/protagonist.h:57:43: error: expected class name
        class SourceAnnotation : public node::ObjectWrap {

**Comment by pksunkara** [comment] 2015-03-04 16:11
@mikevalstar Protagonist 0.17.2 doesn't support node v0.12 yet. We have protagonist-experimental we are beta testing which do support it.

**Comment by pksunkara** [comment] 2015-03-04 16:11
Duplicate of #16

**Closed by pksunkara** 2015-03-04 16:11 UTC
