### ISSUE TITLE
Cannot install on Win7 (x64) with VS 2015 installed 

### ISSUE THREAD

**Issue by m-baumgartner** [apiaryio/protagonist#97] opened 2015-10-14 13:30 UTC
Trying to compile (as part of the `aglio` installation) fails on my station.

I have 
* Windows 7 Pro 64bits.
* Visual Studio community 2015
* npm v2.14.7

I tried using `--msvs-version=2015`,  same result.
I tried setting `msvs-version 2015` in my global npm settings, same result.

Any suggestions?

**Comment by m-baumgartner** [comment] 2015-10-14 15:08
Just tried with Visual Studio community 2013 and `--msvs-version=2015`, same result.

**Comment by m-baumgartner** [comment] 2015-10-14 15:24
I tried with `npm v3.2.2` as suggested [here](https://github.com/nodejs/node-gyp/issues/629#issuecomment-138276692) and it passed !!

 ...Unfortunately for me it failed a bit further when compiling `bufferutil`. Let's investigate on this now...

**Comment by pksunkara** [comment] 2015-10-15 02:37
@m-baumgartner Protagonist on npm doesn't support node 3 and 4 yet.

**Comment by pksunkara** [comment] 2015-10-15 02:38
Can you give us a part of the log?

**Comment by m-baumgartner** [comment] 2015-10-15 11:42
Here is what I have now done : 
* Spin up a new Win7 x64
* Install Windows 7 SDK
* Install Visual Studio Express 2013
* Install node with the built in npm version `v2.14.7`
* run `npm install -g aglio`
-> failed during node-gyp protagonist@0.20.1
Got the following npm-debug.log

>...
35200 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\less-006083667cf0e1b0.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio\node_modules\less
35201 verbose about to build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio
35202 info build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio
35203 info linkStuff aglio-theme-olio@1.2.1
35204 silly linkStuff aglio-theme-olio@1.2.1 has C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules as its parent node_modules
35205 silly linkStuff aglio-theme-olio@1.2.1 is part of a global install
35206 silly linkStuff aglio-theme-olio@1.2.1 is installed into a global node_modules
35207 verbose linkBins aglio-theme-olio@1.2.1
35208 verbose linkMans aglio-theme-olio@1.2.1
35209 verbose rebuildBundles aglio-theme-olio@1.2.1
35210 verbose rebuildBundles [ '.bin',
35210 verbose rebuildBundles   'coffee-script',
35210 verbose rebuildBundles   'highlight.js',
35210 verbose rebuildBundles   'jade',
35210 verbose rebuildBundles   'less',
35210 verbose rebuildBundles   'markdown-it',
35210 verbose rebuildBundles   'markdown-it-anchor',
35210 verbose rebuildBundles   'markdown-it-checkbox',
35210 verbose rebuildBundles   'markdown-it-container',
35210 verbose rebuildBundles   'markdown-it-emoji',
35210 verbose rebuildBundles   'moment',
35210 verbose rebuildBundles   'stylus' ]
35211 info install aglio-theme-olio@1.2.1
35212 info postinstall aglio-theme-olio@1.2.1
35213 verbose unsafe-perm in lifecycle true
35214 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\aglio-theme-olio-a00a87fcb3fdcfac.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\aglio-theme-olio
35215 verbose write writing to C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\package.json
35216 info preinstall protagonist@0.20.1
35217 verbose readDependencies loading dependencies from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\package.json
35218 silly prepareForInstallMany adding nan@~1.8.4 from protagonist dependencies
35219 verbose readDependencies loading dependencies from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\package.json
35220 silly cache add args [ 'nan@~1.8.4', null ]
35221 verbose cache add spec nan@~1.8.4
35222 silly cache add parsed spec Result {
35222 silly cache add   raw: 'nan@~1.8.4',
35222 silly cache add   scope: null,
35222 silly cache add   name: 'nan',
35222 silly cache add   rawSpec: '~1.8.4',
35222 silly cache add   spec: '>=1.8.4 <1.9.0',
35222 silly cache add   type: 'range' }
35223 silly addNamed nan@>=1.8.4 <1.9.0
35224 verbose addNamed ">=1.8.4 <1.9.0" is a valid semver range for nan
35225 silly addNameRange { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: false }
35226 silly mapToRegistry name nan
35227 silly mapToRegistry using default registry
35228 silly mapToRegistry registry https://registry.npmjs.org/
35229 silly mapToRegistry uri https://registry.npmjs.org/nan
35230 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
35231 verbose request uri https://registry.npmjs.org/nan
35232 verbose request no auth needed
35233 info attempt registry request try #1 at 13:32:47
35234 verbose etag "EEJEYBDBWDA07LWTXUI68JUWL"
35235 http request GET https://registry.npmjs.org/nan
35236 http 304 https://registry.npmjs.org/nan
35237 verbose headers { date: 'Thu, 15 Oct 2015 11:32:48 GMT',
35237 verbose headers   via: '1.1 varnish',
35237 verbose headers   'cache-control': 'max-age=60',
35237 verbose headers   etag: '"EEJEYBDBWDA07LWTXUI68JUWL"',
35237 verbose headers   age: '23',
35237 verbose headers   connection: 'keep-alive',
35237 verbose headers   'x-served-by': 'cache-lcy1121-LCY',
35237 verbose headers   'x-cache': 'HIT',
35237 verbose headers   'x-cache-hits': '2',
35237 verbose headers   'x-timer': 'S1444908768.055986,VS0,VE0',
35237 verbose headers   vary: 'Accept' }
35238 silly get cb [ 304,
35238 silly get   { date: 'Thu, 15 Oct 2015 11:32:48 GMT',
35238 silly get     via: '1.1 varnish',
35238 silly get     'cache-control': 'max-age=60',
35238 silly get     etag: '"EEJEYBDBWDA07LWTXUI68JUWL"',
35238 silly get     age: '23',
35238 silly get     connection: 'keep-alive',
35238 silly get     'x-served-by': 'cache-lcy1121-LCY',
35238 silly get     'x-cache': 'HIT',
35238 silly get     'x-cache-hits': '2',
35238 silly get     'x-timer': 'S1444908768.055986,VS0,VE0',
35238 silly get     vary: 'Accept' } ]
35239 verbose etag https://registry.npmjs.org/nan from cache
35240 verbose get saving nan to C:\Users\Dev\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
35241 silly addNameRange number 2 { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: true }
35242 silly addNameRange versions [ 'nan',
35242 silly addNameRange   [ '0.3.0-wip',
35242 silly addNameRange     '0.3.0-wip2',
35242 silly addNameRange     '0.3.0',
35242 silly addNameRange     '0.3.1',
35242 silly addNameRange     '0.3.2',
35242 silly addNameRange     '0.4.0',
35242 silly addNameRange     '0.4.1',
35242 silly addNameRange     '0.4.2',
35242 silly addNameRange     '0.4.3',
35242 silly addNameRange     '0.4.4',
35242 silly addNameRange     '0.5.0',
35242 silly addNameRange     '0.5.1',
35242 silly addNameRange     '0.5.2',
35242 silly addNameRange     '0.6.0',
35242 silly addNameRange     '0.7.0',
35242 silly addNameRange     '0.7.1',
35242 silly addNameRange     '0.8.0',
35242 silly addNameRange     '1.0.0',
35242 silly addNameRange     '1.1.0',
35242 silly addNameRange     '1.1.1',
35242 silly addNameRange     '1.1.2',
35242 silly addNameRange     '1.2.0',
35242 silly addNameRange     '1.3.0',
35242 silly addNameRange     '1.4.0',
35242 silly addNameRange     '1.4.1',
35242 silly addNameRange     '1.5.0',
35242 silly addNameRange     '1.4.2',
35242 silly addNameRange     '1.4.3',
35242 silly addNameRange     '1.5.1',
35242 silly addNameRange     '1.5.2',
35242 silly addNameRange     '1.6.0',
35242 silly addNameRange     '1.5.3',
35242 silly addNameRange     '1.6.1',
35242 silly addNameRange     '1.6.2',
35242 silly addNameRange     '1.7.0',
35242 silly addNameRange     '1.8.0',
35242 silly addNameRange     '1.8.1',
35242 silly addNameRange     '1.8.2',
35242 silly addNameRange     '1.8.3',
35242 silly addNameRange     '1.8.4',
35242 silly addNameRange     '1.9.0',
35242 silly addNameRange     '2.0.0',
35242 silly addNameRange     '2.0.1',
35242 silly addNameRange     '2.0.2',
35242 silly addNameRange     '2.0.3',
35242 silly addNameRange     '2.0.4',
35242 silly addNameRange     '2.0.5',
35242 silly addNameRange     '2.0.6',
35242 silly addNameRange     '2.0.7',
35242 silly addNameRange     '2.0.8',
35242 silly addNameRange     '2.0.9',
35242 silly addNameRange     '2.1.0' ] ]
35243 silly addNamed nan@1.8.4
35244 verbose addNamed "1.8.4" is a plain semver version for nan
35245 silly cache afterAdd nan@1.8.4
35246 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\nan\1.8.4\package\package.json not in flight; writing
35247 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\nan\1.8.4\package\package.json written
35248 silly install resolved [ { name: 'nan',
35248 silly install resolved     version: '1.8.4',
35248 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
35248 silly install resolved     main: 'include_dirs.js',
35248 silly install resolved     repository: { type: 'git', url: 'git://github.com/iojs/nan.git' },
35248 silly install resolved     scripts:
35248 silly install resolved      { test: 'tap --gc test/js/*-test.js',
35248 silly install resolved        'rebuild-tests': 'pangyp rebuild --directory test' },
35248 silly install resolved     contributors:
35248 silly install resolved      [ [Object],
35248 silly install resolved        [Object],
35248 silly install resolved        [Object],
35248 silly install resolved        [Object],
35248 silly install resolved        [Object],
35248 silly install resolved        [Object],
35248 silly install resolved        [Object] ],
35248 silly install resolved     devDependencies:
35248 silly install resolved      { bindings: '~1.2.1',
35248 silly install resolved        'node-gyp': '~1.0.2',
35248 silly install resolved        pangyp: '~2.0.1',
35248 silly install resolved        tap: '~0.7.1',
35248 silly install resolved        xtend: '~4.0.0' },
35248 silly install resolved     license: 'MIT',
35248 silly install resolved     gitHead: 'ed3bbf4ced0cf7937b4e4164766797f71aa97f3d',
35248 silly install resolved     bugs: { url: 'https://github.com/iojs/nan/issues' },
35248 silly install resolved     homepage: 'https://github.com/iojs/nan#readme',
35248 silly install resolved     _id: 'nan@1.8.4',
35248 silly install resolved     _shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
35248 silly install resolved     _from: 'nan@>=1.8.4 <1.9.0',
35248 silly install resolved     _npmVersion: '2.8.3',
35248 silly install resolved     _nodeVersion: '0.12.2',
35248 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
35248 silly install resolved     maintainers: [ [Object], [Object] ],
35248 silly install resolved     dist:
35248 silly install resolved      { shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
35248 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.8.4.tgz' },
35248 silly install resolved     directories: {},
35248 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.8.4.tgz',
35248 silly install resolved     readme: 'ERROR: No README data found!' } ]
35249 info install nan@1.8.4 into C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35250 info installOne nan@1.8.4
35251 verbose installOne of nan to C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist not in flight; installing
35252 verbose lock using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\nan-0db3e0b3f50b1554.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35253 silly install write writing nan 1.8.4 to C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35254 verbose unbuild node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35255 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan is being purged from base C:\Users\Dev\AppData\Roaming\npm
35256 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35257 verbose tar unpack C:\Users\Dev\AppData\Roaming\npm-cache\nan\1.8.4\package.tgz
35258 verbose tar unpacking to C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35259 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan is being purged
35260 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35261 silly gunzTarPerm modes [ '777', '666' ]
35262 silly gunzTarPerm extractEntry package.json
35263 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
35264 silly gunzTarPerm extractEntry README.md
35265 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
35266 silly gunzTarPerm extractEntry include_dirs.js
35267 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 438 ]
35268 silly gunzTarPerm extractEntry LICENSE.md
35269 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
35270 silly gunzTarPerm extractEntry .dntrc
35271 silly gunzTarPerm modified mode [ '.dntrc', 436, 438 ]
35272 silly gunzTarPerm extractEntry appveyor.yml
35273 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 438 ]
35274 silly gunzTarPerm extractEntry nan.h
35275 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
35276 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
35277 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
35278 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
35279 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
35280 silly gunzTarPerm extractEntry nan_new.h
35281 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
35282 silly gunzTarPerm extractEntry nan_string_bytes.h
35283 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 438 ]
35284 silly gunzTarPerm extractEntry CHANGELOG.md
35285 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
35286 verbose write writing to C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan\package.json
35287 info preinstall nan@1.8.4
35288 verbose readDependencies loading dependencies from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan\package.json
35289 verbose readDependencies loading dependencies from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan\package.json
35290 silly install resolved []
35291 verbose about to build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35292 info build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35293 info linkStuff nan@1.8.4
35294 silly linkStuff nan@1.8.4 has C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules as its parent node_modules
35295 silly linkStuff nan@1.8.4 is part of a global install
35296 silly linkStuff nan@1.8.4 is installed into a global node_modules
35297 verbose linkBins nan@1.8.4
35298 verbose linkMans nan@1.8.4
35299 verbose rebuildBundles nan@1.8.4
35300 info install nan@1.8.4
35301 info postinstall nan@1.8.4
35302 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\nan-0db3e0b3f50b1554.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist\node_modules\nan
35303 verbose about to build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35304 info build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35305 info linkStuff protagonist@0.20.1
35306 silly linkStuff protagonist@0.20.1 has C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules as its parent node_modules
35307 silly linkStuff protagonist@0.20.1 is part of a global install
35308 silly linkStuff protagonist@0.20.1 is installed into a global node_modules
35309 verbose linkBins protagonist@0.20.1
35310 verbose linkMans protagonist@0.20.1
35311 verbose rebuildBundles protagonist@0.20.1
35312 verbose rebuildBundles [ 'nan' ]
35313 info install protagonist@0.20.1
35314 verbose unsafe-perm in lifecycle true
35315 info protagonist@0.20.1 Failed to exec install script
35316 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\protagonist-73f9eb1764ab96e0.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35317 verbose about to build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
35318 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\drafter-74a5445cff1c0c9d.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
35319 verbose about to build C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio
35320 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\aglio-0bc89beaac6ee91a.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio
35321 verbose stack Error: protagonist@0.20.1 install: `node-gyp rebuild`
35321 verbose stack Exit status 1
35321 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
35321 verbose stack     at emitTwo (events.js:87:13)
35321 verbose stack     at EventEmitter.emit (events.js:172:7)
35321 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
35321 verbose stack     at emitTwo (events.js:87:13)
35321 verbose stack     at ChildProcess.emit (events.js:172:7)
35321 verbose stack     at maybeClose (internal/child_process.js:818:16)
35321 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
35322 verbose pkgid protagonist@0.20.1
35323 verbose cwd C:\Users\Dev
35324 error Windows_NT 6.1.7601
35325 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "aglio"
35326 error node v4.2.1
35327 error npm  v2.14.7
35328 error code ELIFECYCLE
35329 error protagonist@0.20.1 install: `node-gyp rebuild`
35329 error Exit status 1
35330 error Failed at the protagonist@0.20.1 install script 'node-gyp rebuild'.
35330 error This is most likely a problem with the protagonist package,
35330 error not with npm itself.
35330 error Tell the author that this fails on your system:
35330 error     node-gyp rebuild
35330 error You can get their info via:
35330 error     npm owner ls protagonist
35330 error There is likely additional logging output above.
35331 verbose exit [ 1, true ]
35332 verbose unbuild node_modules\aglio\node_modules\drafter\node_modules\protagonist
35333 info preuninstall protagonist@0.20.1
35334 info uninstall protagonist@0.20.1
35335 verbose unbuild rmStuff protagonist@0.20.1 from C:\Users\Dev\AppData\Roaming\npm\node_modules
35336 verbose unbuild rmStuff in C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules
35337 info postuninstall protagonist@0.20.1
35338 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist is being purged from base C:\Users\Dev\AppData\Roaming\npm
35339 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35340 silly vacuum-fs purging C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules\protagonist
35341 silly vacuum-fs quitting because other entries in C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter\node_modules
35342 verbose unbuild node_modules\aglio\node_modules\drafter
35343 info preuninstall drafter@0.2.8
35344 info uninstall drafter@0.2.8
35345 verbose unbuild rmStuff drafter@0.2.8 from C:\Users\Dev\AppData\Roaming\npm\node_modules
35346 verbose unbuild rmStuff in C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules
35347 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter.cmd is being gently removed
35348 silly gentlyRm verifying C:\Users\Dev\AppData\Roaming\npm is an npm working directory
35349 silly gentlyRm containing path C:\Users\Dev\AppData\Roaming\npm is under npm's control, in C:\Users\Dev\AppData\Roaming\npm
35350 silly gentlyRm deletion target C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter.cmd is under C:\Users\Dev\AppData\Roaming\npm
35351 verbose gentlyRm vacuuming from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter.cmd up to C:\Users\Dev\AppData\Roaming\npm
35352 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter is being gently removed
35353 silly gentlyRm verifying C:\Users\Dev\AppData\Roaming\npm is an npm working directory
35354 silly gentlyRm containing path C:\Users\Dev\AppData\Roaming\npm is under npm's control, in C:\Users\Dev\AppData\Roaming\npm
35355 silly gentlyRm deletion target C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter is under C:\Users\Dev\AppData\Roaming\npm
35356 verbose gentlyRm vacuuming from C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\.bin\drafter up to C:\Users\Dev\AppData\Roaming\npm
35357 info postuninstall drafter@0.2.8
35358 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter is being purged from base C:\Users\Dev\AppData\Roaming\npm
35359 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
35360 silly vacuum-fs purging C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules\drafter
35361 silly vacuum-fs quitting because other entries in C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio\node_modules
35362 verbose unbuild node_modules\aglio
35363 info preuninstall aglio@2.1.1
35364 info uninstall aglio@2.1.1
35365 verbose unbuild rmStuff aglio@2.1.1 from C:\Users\Dev\AppData\Roaming\npm\node_modules
35366 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\aglio.cmd is being gently removed
35367 silly gentlyRm verifying C:\Users\Dev\AppData\Roaming\npm is an npm working directory
35368 silly gentlyRm containing path C:\Users\Dev\AppData\Roaming\npm is under npm's control, in C:\Users\Dev\AppData\Roaming\npm
35369 silly gentlyRm deletion target C:\Users\Dev\AppData\Roaming\npm\aglio.cmd is under C:\Users\Dev\AppData\Roaming\npm
35370 verbose gentlyRm vacuuming from C:\Users\Dev\AppData\Roaming\npm\aglio.cmd up to C:\Users\Dev\AppData\Roaming\npm
35371 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\aglio is being gently removed
35372 silly gentlyRm verifying C:\Users\Dev\AppData\Roaming\npm is an npm working directory
35373 silly gentlyRm containing path C:\Users\Dev\AppData\Roaming\npm is under npm's control, in C:\Users\Dev\AppData\Roaming\npm
35374 silly gentlyRm deletion target C:\Users\Dev\AppData\Roaming\npm\aglio is under C:\Users\Dev\AppData\Roaming\npm
35375 verbose gentlyRm vacuuming from C:\Users\Dev\AppData\Roaming\npm\aglio up to C:\Users\Dev\AppData\Roaming\npm
35376 info postuninstall aglio@2.1.1
35377 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio is being purged from base C:\Users\Dev\AppData\Roaming\npm
35378 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio
35379 silly vacuum-fs purging C:\Users\Dev\AppData\Roaming\npm\node_modules\aglio
35380 silly vacuum-fs removing C:\Users\Dev\AppData\Roaming\npm\node_modules
35381 silly vacuum-fs finished vacuuming up to C:\Users\Dev\AppData\Roaming\npm

**Comment by pksunkara** [comment] 2015-10-16 08:33
This looks like it's an issue when building protagonist using `node-gyp`. Do you have Python 2.7.9 installed?

**Comment by m-baumgartner** [comment] 2015-10-16 08:38
I have the x64 version of python 2.7.10

**Comment by m-baumgartner** [comment] 2015-10-16 09:29
FYI, I tried with a 32bit version of python 2.7.10. Sill fails

**Comment by m-baumgartner** [comment] 2015-10-19 10:05
Any suggestions?

**Comment by kylef** [comment] 2015-10-21 17:42
Hi,

Sorry for the delay in responding. As @pksunkara mentioned before, Node 3/4 isn't yet supported. It will be in the next release of Protagonist. For now you will need to use older versions.

The above output you pasted shows this was from node v4.

```
error node v4.2.1
```

There are two options you have at the moment:

- Use an older version of node.
- Build aglio and protagonist from source on GitHub. The master branch of Protagonist includes support for Node 4. Aglio has been updated in master to support the newer Protagonist.

**Comment by kylef** [comment] 2015-10-21 17:43
Closing as a duplicate of #81.

**Closed by kylef** 2015-10-21 17:43 UTC
