### ISSUE TITLE
Install failed in windows with VC2013 express

### ISSUE THREAD

**Issue by rick-li** [apiaryio/protagonist#54] opened 2015-03-25 01:31 UTC
Hi, I tried to npm install protagonist, but failed, I tried to build from source but still failed with same errors:

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  libmarkdownparser.vcxproj -> c:\apps\projects\protagonist\build\Release\\libmarkdownparser.lib
  libsnowcrash.vcxproj -> c:\apps\projects\protagonist\build\Release\\libsnowcrash.lib
  libsundown.vcxproj -> c:\apps\projects\protagonist\build\Release\\libsundown.lib
  annotation.cc
  blueprint.cc
  sourcemap.cc
  parse.cc
  protagonist.cc
  result.cc
c:\apps\projects\protagonist\src\protagonist.h(13): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(13): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(35): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(35): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(50): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(50): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(57): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(57): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(69): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(69): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(69): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(76): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(76): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(92): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(92): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(99): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(99): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(99): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(13): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(13): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(28): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(19): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
          c:\Users\kl68884\.node-gyp\0.12.0\deps\v8\include\v8.h(816) : see declaration of 'v8::HandleScope::HandleScope'
          c:\Users\kl68884\.node-gyp\0.12.0\deps\v8\include\v8.h(800) : see declaration of 'v8::HandleScope'
c:\apps\projects\protagonist\src\protagonist.h(35): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(21): error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
c:\apps\projects\protagonist\src\protagonist.h(35): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(23): error C2039: 'NewSymbol' : is not a member of 'v8::String' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
          c:\Users\kl68884\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
..\src\sourcemap.cc(23): error C3861: 'NewSymbol': identifier not found [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(50): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(25): error C2660: 'v8::PersistentBase<T>::New' : function does not take 1 arguments [c:\apps\projects\protagonist\build\protagonist.vcxproj]
          with
          [
              T=v8::Function
          ]
c:\apps\projects\protagonist\src\protagonist.h(50): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(26): error C2039: 'NewSymbol' : is not a member of 'v8::String' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
          c:\Users\kl68884\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
c:\apps\projects\protagonist\src\protagonist.h(57): error C2039: 'ObjectWrap' : is not a member of 'node' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(26): error C3861: 'NewSymbol': identifier not found [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(57): error C2504: 'ObjectWrap' : base class undefined [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(29): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\apps\projects\protagonist\build\protagonist.vcxproj]
..\src\sourcemap.cc(29): error C2143: syntax error : missing ',' before '&' [c:\apps\projects\protagonist\build\protagonist.vcxproj]
c:\apps\projects\protagonist\src\protagonist.h(69): error C2039: 'Arguments' : is not a member of 'v8' [c:\apps\projects\protagonist\build\pr

**Comment by klokane** [comment] 2015-03-25 14:17
Which version of node you are runninng?

**Comment by rick-li** [comment] 2015-03-25 14:18
v0.12.0

**Comment by klokane** [comment] 2015-03-25 14:23
ok will check

**Comment by pksunkara** [comment] 2015-03-25 14:54
Hello @rick-li, The protagonist version 0.17.x and lower does not support node 0.12. You can use our pre-release version `protagonist@0.19.0-rc` or wait until we release protagonist to be able to run it on node 0.12.

**Comment by pksunkara** [comment] 2015-03-25 14:54
Duplicate of #16

**Closed by pksunkara** 2015-03-25 14:54 UTC
